Review the homework for lesson 5
adrek22/aqa_python_course pull request #3
Opened 2024-03-09 16:40 UTC by adrek22

There 2 files with different versions of task 3 completion:
_v01 - less code: exception is shown and loop is restarted after all inputs are entered containing invalid input
_v02 - more code: exception is shown and loop is restarted for each invalid input

2024-03-10 15:08 UTC, dyakov22 requested changes
Немає власного виключення для першого завдання

2024-03-10 15:08 UTC, dyakov22 commented on homework_dir/homework5_v01.py
> +    except Exception as e:
не треба було його відловлювати

2024-03-10 15:08 UTC, dyakov22 commented on homework_dir/homework5_v01.py
> +        if user_input2.lower() == 'q':
забагато перевірок
повинен бути один вихід

2024-03-10 15:08 UTC, dyakov22 commented on homework_dir/homework5_v01.py
> +    print('Task 2: Square Root Calculation with All Exceptions Handling'.center(50))
не треба цього робити, ми намагаємось отримати чистий код
я і так розумію що відбувавється

2024-03-10 20:27 UTC, adrek22 commented
Додав власне виключення для першого завдання, оптимізував код.

2024-03-11 09:09 UTC, adrek22 commented on homework_dir/homework5_v01.py
> +    except Exception as e:
Я створив власне виключення. То його потрібно відловлювати?

2024-03-11 09:09 UTC, adrek22 commented on homework_dir/homework5_v01.py
> +    except Exception as e:
Я створив власне виключення. То ж його потрібно відловлювати?

2024-03-11 09:10 UTC, adrek22 commented on homework_dir/homework5_v01.py
> +        if user_input2.lower() == 'q':
лишив тільки 1

2024-03-11 09:10 UTC, adrek22 commented on homework_dir/homework5_v01.py
> +    print('Task 2: Square Root Calculation with All Exceptions Handling'.center(50))
Гаразд приберу звідси і з шаблону

2024-03-11 17:20 UTC, merged