Review the homework for lesson 10
adrek22/aqa_python_course pull request #9
Opened 2024-03-28 12:19 UTC by adrek22

2024-03-28 13:12 UTC, dyakov22 requested changes

2024-03-28 13:12 UTC, dyakov22 commented on homework_dir/homework10_v01.py
> +            print("-" * 80)  # Separator
в задачі не було написано про додавання після виконання функції

2024-03-28 13:12 UTC, dyakov22 commented on homework_dir/homework10_v01.py
> +        if duration < 1:
в задачі не було нічого про різний вивід при різних дюрейшенах

2024-03-28 14:21 UTC, adrek22 commented on homework_dir/homework10_v01.py
> +            print("-" * 80)  # Separator
додав homework10_v02_expected.py із забраним сепаратором

2024-03-28 14:21 UTC, adrek22 commented on homework_dir/homework10_v01.py
> +        if duration < 1:
додав homework10_v02_expected.py із забраним надлишковим кодом

2024-03-29 12:14 UTC, dyakov22 commented on homework_dir/homework10_v02_expected.py
> +task_number = input("Please select a task, 1 or 2: ")
не треба це додавати кожного разу

2024-03-29 12:14 UTC, dyakov22 approved these changes

2024-03-29 16:55 UTC, adrek22 commented on homework_dir/homework10_v02_expected.py
> +task_number = input("Please select a task, 1 or 2: ")
гаразд, на другий раз буду дві версії готувати:
таку, яка мені подобається
і таку, яка тобі подобається

2024-03-31 10:11 UTC, dyakov22 commented on homework_dir/homework10_v02_expected.py
> +task_number = input("Please select a task, 1 or 2: ")
Це не питання у вподобаннях, а питання у задачі котра стоїть
В данному випадку є дз, котре проецюється на задачу проекту і у випадку проекту зайвий код заважає, тому що коли в тебе буде хоча б 100 тестів у проекті на різні модулі, то коду і так буде вдосталь 
Якщо є додаткові питання то пиши, можемо обсудити, тільки пиши у телеграмі, тому що цей коментар я побачив випадково

2024-04-04 20:55 UTC, merged